build_ex1: ex1compile ex1exe clean

ex1compile: 
	gcc ex1.c -o ex1

ex1exe:
	./ex1

build_ex2: ex2compile ex2exe

ex2compile: 
	gcc ex2.c -o ex2

ex2exe:
	./ex2

build_ex3: ex3compile ex3exe

ex3compile: 
	gcc ex3.c -o ex3

ex3exe:
	./ex3

clean:
	@rm -f *.o ex1 ex2 ex3
